spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-usuarios
          uri: http://ms-usuarios:8081
          predicates:
            - Path=/api/usuarios/**

        - id: ms-libros
          uri: http://ms-libros:8082
          predicates:
            - Path=/api/libros/**

        - id: ms-autores
          uri: http://ms-autores:8083
          predicates:
            - Path=/api/autores/**

        - id: ms-categorias
          uri: http://ms-categorias:8084
          predicates:
            - Path=/api/categorias/**

        - id: ms-prestamos
          uri: http://ms-prestamos:8085
          predicates:
            - Path=/api/prestamos/**

        - id: ms-reservas
          uri: http://ms-reservas:8086
          predicates:
            - Path=/api/reservas/**

        - id: ms-multas
          uri: http://ms-multas:8087
          predicates:
            - Path=/api/multas/**

        - id: ms-sedes
          uri: http://ms-sedes:8088
          predicates:
            - Path=/api/sedes/**

        - id: ms-notificaciones
          uri: http://ms-notificaciones:8089
          predicates:
            - Path=/api/notificaciones/**

        - id: ms-catalogacion
          uri: http://ms-catalogacion:8090
          predicates:
            - Path=/api/catalogacion/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info